branch-defaults:
  develop:
    environment: null
    group_suffix: null
global:
  application_name: uwalk
  default_ec2_keyname: uwalk-eb-deploy
  default_platform: Node.js
  default_region: us-west-1
  profile: eb-cli
  sc: git
