branch-defaults:
  develop:
    environment: uwalk
global:
  application_name: uwalk
  default_ec2_keyname: aws-eb-construction
  default_platform: 64bit Amazon Linux 2015.03 v2.0.1 running Node.js
  default_region: us-west-1
  profile: eb-cli
  sc: git
